# Generated by Django 3.1.7 on 2021-03-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210326_1155'),
        ('vignettes', '0002_vignette_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vignette',
            old_name='vignette_type',
            new_name='id_vignette_type',
        ),
        migrations.AddField(
            model_name='vignette',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
            preserve_default=False,
        ),
    ]
