# Generated by Django 3.1.7 on 2021-03-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vignettes', '0003_auto_20210326_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vignette',
            old_name='licence_plate',
            new_name='license_plate',
        ),
    ]
