# Generated by Django 3.1.7 on 2021-04-26 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vignettes', '0003_auto_20210413_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='vignette',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
