# Generated by Django 3.1.7 on 2021-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vignettes', '0004_auto_20210326_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vignette',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vignette',
            old_name='id_vignette_type',
            new_name='vignette_type',
        ),
    ]
