# Generated by Django 3.1.7 on 2021-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vignettes', '0004_vignette_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vignette',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
