# Generated by Django 3.1.7 on 2021-03-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VignetteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=25)),
                ('valid_from', models.DateTimeField()),
                ('licence_plate', models.CharField(max_length=8)),
                ('vignette_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vignette.vignettetype')),
            ],
        ),
    ]
