# Generated by Django 3.1.7 on 2021-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('invalid', models.IntegerField()),
                ('generated', models.DateTimeField()),
            ],
        ),
    ]
